//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeAreReady.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int LogId { get; set; }
        public System.Guid UserProfileId { get; set; }
        public int CheckPointId { get; set; }
        public string Action { get; set; }
        public int AppUserId { get; set; }
        public System.DateTime LogTime { get; set; }
    
        public virtual CheckPoint CheckPoint { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
