//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeAreReady.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.Logs = new HashSet<Log>();
        }
    
        public System.Guid UserProfileId { get; set; }
        public string NFCTagId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public int Age { get; set; }
        public string BloodGroup { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> GroupCount { get; set; }
        public string EmergencyContact { get; set; }
        public string EmergencyContactNumber { get; set; }
        public string SMSPackPurchased { get; set; }
        public System.DateTime FirstScanDateTime { get; set; }
        public Nullable<int> FirstCheckpointId { get; set; }
        public Nullable<System.DateTime> LastScanDateTime { get; set; }
        public Nullable<int> LastCheckPointId { get; set; }
        public string MedicalCondition { get; set; }
        public int AppUserId { get; set; }
        public string TagReclaimed { get; set; }
    
        public virtual ICollection<Log> Logs { get; set; }
    }
}
